language: python
sudo: false
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install quantpy
  - pip install -U pip wheel
  - pip install cython
  - git clone https://github.com/cupy/cupy.git
  - cd cupy
  - python setup.py sdist --cupy-no-cuda
  - cd ../
  - rm -r ./cupy
before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
notifications:
  email: false
